---
title: "{{SO_WHAT}}"
---
quadrantChart
    title {{TITLE}}
    x-axis "{{X_LOW}}" --> "{{X_HIGH}}"
    y-axis "{{Y_LOW}}" --> "{{Y_HIGH}}"
    quadrant-1 "{{Q1}}"
    quadrant-2 "{{Q2}}"
    quadrant-3 "{{Q3}}"
    quadrant-4 "{{Q4}}"
