---
title: "{{SO_WHAT}}"
---
graph TD
    Z["{{SO_WHAT}}"]:::top
    A1["{{ARG_1}}"]:::lvl1
    A2["{{ARG_2}}"]:::lvl1
    A3["{{ARG_3}}"]:::lvl1
    Z --> A1
    Z --> A2
    Z --> A3

    classDef top fill:{{PRIMARY}},color:#fff,stroke:{{PRIMARY}},stroke-width:2px,font-weight:bold,font-size:18px
    classDef lvl1 fill:{{SECONDARY}},color:#fff,stroke:{{SECONDARY}},stroke-width:1px,font-size:14px
